name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
       fetch-depth: 0
       
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'maven'

    - uses: Keeper-Security/ksm-action@v1
      with:
        keeper-secret-config: ${{ secrets.KSM_CONFIG }}
        secrets: |
          ${{ vars.KEEPER_SONARCLOUD_RECORD_ID }}/field/password > env:SONAR_TOKEN
        
    - name: Build and test
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: ./mvnw -B clean verify sonar:sonar -Dsonar.scanner.force-deprecated-java-version=true